# Generated by Django 4.2.5 on 2023-10-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_rename_name_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='answer',
            field=models.TextField(blank=True, default=models.TextField(max_length=32), max_length=32),
        ),
    ]
