# Generated by Django 4.2.5 on 2023-10-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_prompt_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='answer',
            field=models.TextField(blank=True, default='[Blank]', max_length=32),
        ),
    ]
